### PR TITLE
Use rack ~> 3.0

### PR DESCRIPTION
**Pull request by mfaughn**
The dependency on a now archaic version of rack has been a real thorn.  This fork includes a bare minimum of changes in order to get Innate working with the current version of rack.  All bacon tests are passing.

### CODE REVIEW

**Comment by manveru** [comment]
Thanks for the PR!
I honestly didn't think anybody was still using Innate (including myself), so I've put off changing anything for years.
Would you mind if I add you to the maintainers of this repository?

**Comment by mfaughn** [comment]
Ha. I know of one other person still using Innate / Ramaze.  It spins out of a small company that put together a pretty large and complicated set of tools that more or less automatically creates web applications from UML diagrams.  Ramaze was baked into that more than 10 years ago.  The team of people maintaining that toolchain has dwindled down to just me.  I very much want to replace Ramaze with something modern with a large community behind it but am not being given the bandwidth to do so.  Alleviating the old rack dependency is a stopgap that at least relieves me of some immediate roadblocks and is quicker than replacing Ramaze.

I've got no problem becoming a maintainer.  Ramaze too if that helps.  I'm working on that one now.  Everything passing except the tests with Redis and memcached.

**Comment by manveru** [comment]
Alright, I published the new version to rubygems. Also added you to the maintainers. Thanks again.

**Comment by Pistos** [comment]
> I honestly didn't think anybody was still using Innate (including myself)

I actually still have an old codebase or two kicking around which uses it, which I still base some new code off of, once in a while.

Thanks for your contributions, @mfaughn .

**Pull request merged**
